name: Virtual Plant

on:
  push:
  schedule:
    - cron: '1 1 * * *'

jobs:
  water:
    name: water_plant
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: watering the plants
        run: sh ./water.sh
