name: Virtual Plant

on:
  push:
  schedule:
    - cron: '1 1 * * *'

jobs:
  water:
    name: water_plant
    runs-on: ubuntu-latest

    steps:
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: run the water script
        run: python ./water.py

      - name: watering the plants
        run: sh ./water.sh
